# -*- mode: python ; coding: utf-8 -*-
# Hidden imports discovered via runtime module tracing (sys.modules analysis)
# on the exact package versions used in build.yml — this list is complete.

a = Analysis(
    ['main_dpg.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('icon.ico', '.'),
    ],
    hiddenimports=[
        # stdlib — pandas/numpy pull these in but PyInstaller misses them
        'secrets', 'hmac', 'hashlib', 'decimal', 'fractions',
        'calendar', 'csv', 'lzma', 'bz2', 'zipfile', 'zlib',
        'xml', 'xml.etree', 'xml.etree.ElementTree',
        'xml.parsers', 'xml.parsers.expat',
        'urllib', 'urllib.parse',
        # numpy
        'numpy', 'numpy._core', 'numpy._core._multiarray_umath',
        'numpy._distributor_init', 'numpy._globals',
        'numpy.core', 'numpy.core._multiarray_umath',
        'numpy.core._multiarray_tests', 'numpy.core.multiarray',
        'numpy.core.numeric', 'numpy.core.umath',
        'numpy.core._dtype_ctypes', 'numpy.core._methods',
        'numpy.core.arrayprint', 'numpy.core.fromnumeric',
        'numpy.core.function_base', 'numpy.core.getlimits',
        'numpy.core.overrides', 'numpy.core.shape_base',
        'numpy.dtypes', 'numpy.exceptions',
        'numpy.lib', 'numpy.lib.stride_tricks', 'numpy.lib.format',
        'numpy.lib.arraypad', 'numpy.lib.arraysetops',
        'numpy.lib.function_base', 'numpy.lib.histograms',
        'numpy.lib.index_tricks', 'numpy.lib.npyio',
        'numpy.lib.polynomial', 'numpy.lib.shape_base',
        'numpy.lib.type_check', 'numpy.lib.ufunclike',
        'numpy.linalg', 'numpy.linalg._umath_linalg',
        'numpy.fft', 'numpy.fft._pocketfft',
        'numpy.ma', 'numpy.ma.core', 'numpy.ma.extras',
        'numpy.matrixlib', 'numpy.matrixlib.defmatrix',
        'numpy.polynomial', 'numpy.polynomial.polynomial',
        'numpy.random', 'numpy.random._generator',
        'numpy.random._bounded_integers', 'numpy.random.mtrand',
        'numpy.random.bit_generator',
        # pandas — _libs C extensions are the ones PyInstaller misses
        'pandas', 'pandas._libs', 'pandas._libs.lib',
        'pandas._libs.algos', 'pandas._libs.arrays',
        'pandas._libs.groupby', 'pandas._libs.hashing',
        'pandas._libs.hashtable', 'pandas._libs.index',
        'pandas._libs.indexing', 'pandas._libs.internals',
        'pandas._libs.interval', 'pandas._libs.join',
        'pandas._libs.json', 'pandas._libs.missing',
        'pandas._libs.ops', 'pandas._libs.parsers',
        'pandas._libs.properties', 'pandas._libs.reshape',
        'pandas._libs.sparse', 'pandas._libs.tslib',
        'pandas._libs.tslibs', 'pandas._libs.tslibs.base',
        'pandas._libs.tslibs.ccalendar',
        'pandas._libs.tslibs.conversion',
        'pandas._libs.tslibs.dtypes',
        'pandas._libs.tslibs.nattype',
        'pandas._libs.tslibs.np_datetime',
        'pandas._libs.tslibs.offsets',
        'pandas._libs.tslibs.parsing',
        'pandas._libs.tslibs.period',
        'pandas._libs.tslibs.strptime',
        'pandas._libs.tslibs.timestamps',
        'pandas._libs.tslibs.timedeltas',
        'pandas._libs.tslibs.timezones',
        'pandas._libs.tslibs.tzconversion',
        'pandas._libs.tslibs.vectorized',
        'pandas._libs.window', 'pandas._libs.window.aggregations',
        'pandas._libs.window.indexers', 'pandas._libs.writers',
        'pandas._version_meson',
        'pandas.core', 'pandas.core.frame', 'pandas.core.series',
        'pandas.core.indexes', 'pandas.core.indexes.base',
        'pandas.core.indexes.range', 'pandas.core.indexes.multi',
        'pandas.core.arrays', 'pandas.core.arrays.masked',
        'pandas.core.arrays.integer', 'pandas.core.arrays.floating',
        'pandas.core.arrays.boolean', 'pandas.core.arrays.string_',
        'pandas.core.dtypes', 'pandas.core.dtypes.common',
        'pandas.core.dtypes.cast', 'pandas.core.dtypes.dtypes',
        'pandas.core.construction', 'pandas.core.internals',
        'pandas.core.internals.blocks',
        'pandas.core.internals.managers',
        'pandas.io', 'pandas.io.excel', 'pandas.io.excel._base',
        'pandas.io.excel._openpyxl', 'pandas.io.excel._xlrd',
        'pandas.io.parsers', 'pandas.io.parsers.readers',
        'pandas.io.parsers.base_parser',
        'pandas.io.parsers.c_parser_wrapper',
        'pandas.io.parsers.python_parser',
        'pandas.io.common', 'pandas.io.formats',
        'pandas.io.formats.format',
        'pandas.compat', 'pandas.compat._optional',
        'pandas.compat.numpy', 'pandas.compat.numpy.function',
        'pandas._config', 'pandas._config.config', 'pandas._typing',
        # openpyxl
        'openpyxl', 'openpyxl.styles', 'openpyxl.utils',
        'openpyxl.workbook', 'openpyxl.workbook.workbook',
        'openpyxl.worksheet', 'openpyxl.worksheet.worksheet',
        'openpyxl.worksheet._writer', 'openpyxl.worksheet._reader',
        'openpyxl.cell', 'openpyxl.cell.cell',
        'openpyxl.reader', 'openpyxl.reader.excel',
        'openpyxl.writer', 'openpyxl.writer.excel',
        'openpyxl.packaging', 'openpyxl.packaging.manifest',
        'openpyxl.styles.stylesheet', 'openpyxl.styles.named_styles',
        'openpyxl.styles.fonts', 'openpyxl.styles.fills',
        'openpyxl.styles.borders', 'openpyxl.styles.alignment',
        'openpyxl.styles.numbers', 'openpyxl.utils.cell',
        'openpyxl.utils.datetime', 'openpyxl.descriptors',
        'openpyxl.descriptors.serialisable',
        'openpyxl.xml', 'openpyxl.xml.functions',
        'openpyxl.xml.constants',
        # DearPyGui
        'dearpygui', 'dearpygui.dearpygui', 'dearpygui._dearpygui',
        # SQLite
        'sqlite3', '_sqlite3', 'sqlite3.dbapi2',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'customtkinter', 'PIL', 'test', 'unittest'],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='BeerCount',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    icon='icon.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name='BeerCount',
)
