name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dearpygui
          pip install openpyxl==3.1.2
          pip install pandas
          pip install pyinstaller==6.3.0

      - name: Build EXE
        run: pyinstaller BeerCount.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: BeerCount_Windows
          path: dist/BeerCount/
